### ISSUE TITLE
Change diagram to reflect changes introduced in Milestone 3

### ISSUE THREAD

**Issue by ondrejbudai** [monster-slayers/web-is#126]
- [x] cannot delete hero
- [x] cannot delete job
- [x] status moved from user to hero
